### ISSUE TITLE
Amount of time

### ISSUE THREAD

**Issue by charlesreid1** [guillaume-chevalier/Hyperopt-Keras-CNN-CIFAR-100#2]
Hi, really enjoying this repository. Your work is well-done and has gotten me interested in some practical ways to automate hyperoptimization. I was wondering if you might add some information to the readme to give folks a sense for how long a parameter study this extensive takes, and what kind of hardware you used. What kind of GPUs, and were any parts parallelizable? Did it take on the order of hours, days, or weeks?

Thanks!

**Comment by guillaume-chevalier** [comment]
If I remember well, it took on the order of a week to run the whole thing (without TensorBoard and without the edits made for Vooban).
